sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- pypy
install:
- pip install codecov
- pip install tox
- TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}
script: tox -e $TOX_ENV
after_success:
- codecov
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: davidemoro
  password:
    secure: Gy73d43FKfm4jxoAaq3/WwSJH04+WCTjyPxulbxbA3vlLpcDrBDxgT4BUEqr1VBGKurYEnCZzrU+scmqGnaDQkUWmxAZsA9ghCnWa8uhhfajzpY56xUg2AWoGGxwfyZB8Yem/ZsmnbfImVfnedzNiNHaZsBGTdTmCoy85OxmtQmAbkysWOBe7MOlJe3AY053uTDbTWy4Tp0oC0gMi1cJl7hYdouXBmtPnMTEVVeSk3XVRePJrUD5Lbz75bRxyKvZcGhpEZEUoBYWmxJoU432ko6R/F5zucGdFtVZh+hiZwxKWKTeXEY5DdE6msJ6JEHAJMrRXPNPYLf4U+6Zu0kwvTo7jI7iZELYg3eswjGCIHZZE6fbU35Kv1Wsh5aT9FlEsrI+6C2u6yiLtbHt4gmdfJ0qI4WJ9bmXvGa+7osJeaI96k/g7efO4KKdALp+fDT9BpWEROJ5SuCvjEsTQKl5om7oxehttj4m4rzKTxFNg0JOz9U5zDYBTcWk2VDisPRHLa15VO4iQIehJ4VcktGyttRxLjsQBSh6TiLp9hjGzvJ/ZV+4dZPadAHitSfiMwvHkUV6ysSIi1ScjEt2BXc9SBkJm6cQIq0KpHYAMvWLQQuk5pkP24CbpcYHGLmVd0MedL1Cmxl/ygppxRtUx5bYvydxBj/yqugJBKCFJEnJaUU=
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: davidemoro/pytest-pypom-navigation
